---
meta:
  environment: db-dumper-service-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: just_install_packages
    networks:
      - name: db_dumper_service1

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: db_dumper_service1
  type: manual
  subnets:
  - range: 10.244.68.0/24
    name: db_dumper_service1
    gateway: 10.244.68.1
    static:
      - 10.244.68.2 - 10.244.68.60
